# Generated by Django 5.0.2 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_ai', models.CharField(max_length=100)),
                ('last_message_human', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'message',
            },
        ),
    ]
