# Generated by Django 5.0.2 on 2024-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='output',
        ),
    ]
